language: python
python:
  - "2.7"
cache: pip
dist: trusty
sudo: false
install:
  - make install
script:
  - make test
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: XdjTEiXO+wBt8/MmW19uDAZxAqL4XJSHXtIPkJxMPSjfyy3u+GoXQWQULI9YVdksOvLlQ/vuZofS2xDUuQJIFSyS/evrmBFESVTzlkLKcagUc5pF6fAavzeR+IV4vIvn3r4R7R3xsQWYqMnhDpIqaAamkDIcYJGLqIWra3gDzvQ=
  local_dir: output/
  repo: kura.github.io
  target_branch: master
  on:
    branch: master

