language: python
python:
  - "2.7"
cache: pip
dist: trusty
sudo: false
group: edge
install:
  - make install
script:
  - make test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output/
  repo: kura.github.io
  target_branch: master
  on:
    branch: master

